### ISSUE TITLE
Exception: Invalid json in get_vehicle_information

### ISSUE THREAD

**Issue by lighty78** [audiconnect/audi_connect_ha#106]
Running latest HA. 
**core-2021.12.9**
Getting this in the log when starting the addon. Tried to reinstall but getting same error.

Logginformation (FEL)
This error originated from a custom integration.
Logger: homeassistant.config_entries
Source: custom_components/audiconnect/audi_services.py:257
Integration: Audi Connect
First occurred: 13:39:16 (1 occurrences)
Last logged: 13:39:16

Error setting up entry per.*****@***mail.com for audiconnect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/audiconnect/__init__.py", line 106, in async_setup_entry
    return await data.update(utcnow())
  File "/config/custom_components/audiconnect/audi_account.py", line 162, in update
    if not await self.connection.update(None):
  File "/config/custom_components/audiconnect/audi_connect_account.py", line 113, in update
    vehicles_response = await self._audi_service.get_vehicle_information()
  File "/config/custom_components/audiconnect/audi_services.py", line 257, in get_vehicle_information
    raise Exception("Invalid json in get_vehicle_information")
Exception: Invalid json in get_vehicle_information

**It´s working again. Don´t know what changed. But this is solved.**

**Comment by coreywillwhat** [comment]
closing based on comment.
