### ISSUE TITLE
State max length is 255 characters.

### ISSUE THREAD

**Issue by rklomp** [audiconnect/audi_connect_ha#113]
Receiving errors below since pull request #104

```
Logger: homeassistant.util.logging
Source: util/logging.py:105
First occurred: 22:42:50 (28 occurrences)
Last logged: 23:43:06

Exception in async_schedule_update_ha_state when dispatching 'audiconnect.updated': () Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 685, in async_schedule_update_ha_state self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state self.hass.states.async_set( File "/usr/src/homeassistant/homeassistant/core.py", line 1357, in async_set state = State( File "/usr/src/homeassistant/homeassistant/core.py", line 1045, in __init__ raise InvalidStateError( homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.none_longterm_trip_user_reset. State max length is 255 characters.
Exception in async_schedule_update_ha_state when dispatching 'audiconnect.updated': () Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 685, in async_schedule_update_ha_state self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state self.hass.states.async_set( File "/usr/src/homeassistant/homeassistant/core.py", line 1357, in async_set state = State( File "/usr/src/homeassistant/homeassistant/core.py", line 1045, in __init__ raise InvalidStateError( homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.none_longterm_trip_data. State max length is 255 characters.
Exception in async_schedule_update_ha_state when dispatching 'audiconnect.updated': () Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 685, in async_schedule_update_ha_state self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state self.hass.states.async_set( File "/usr/src/homeassistant/homeassistant/core.py", line 1357, in async_set state = State( File "/usr/src/homeassistant/homeassistant/core.py", line 1045, in __init__ raise InvalidStateError( homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.none_shortterm_trip_data. State max length is 255 characters.
Exception in async_schedule_update_ha_state when dispatching 'audiconnect.updated': () Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 685, in async_schedule_update_ha_state self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state self.hass.states.async_set( File "/usr/src/homeassistant/homeassistant/core.py", line 1357, in async_set state = State( File "/usr/src/homeassistant/homeassistant/core.py", line 1045, in __init__ raise InvalidStateError( homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.none_shortterm_trip_user_reset. State max length is 255 characters.
```

```
Logger: homeassistant.components.sensor
Source: core.py:1045
Integration: Sensor (documentation, issues)
First occurred: 22:32:48 (2 occurrences)
Last logged: 22:32:48

Error adding entities for domain sensor with platform audiconnect
Error while setting up audiconnect platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 773, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1357, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1045, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.none_longterm_trip_user_reset. State max length is 255 characters.
```

**Comment by brhahlen** [comment]
Same issue here

**Comment by whoisdecoy** [comment]
Likewise, this is a bit insane!! 11976 occurrences

```
Logger: homeassistant.util.logging
Source: util/logging.py:114
First occurred: April 7, 2022, 9:01:29 PM (11976 occurrences)
Last logged: 8:48:15 PM

Exception in async_schedule_update_ha_state when dispatching 'audiconnect.updated': () Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 712, in async_schedule_update_ha_state self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 553, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 681, in _async_write_ha_state self.hass.states.async_set( File "/usr/src/homeassistant/homeassistant/core.py", line 1363, in async_set state = State( File "/usr/src/homeassistant/homeassistant/core.py", line 1049, in __init__ raise InvalidStateError( homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.q5_shortterm_trip_user_reset. State max length is 255 characters.
Exception in async_schedule_update_ha_state when dispatching 'audiconnect.updated': () Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 712, in async_schedule_update_ha_state self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 553, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 681, in _async_write_ha_state self.hass.states.async_set( File "/usr/src/homeassistant/homeassistant/core.py", line 1363, in async_set state = State( File "/usr/src/homeassistant/homeassistant/core.py", line 1049, in __init__ raise InvalidStateError( homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.q5_longterm_trip_user_reset. State max length is 255 characters.
Exception in async_schedule_update_ha_state when dispatching 'audiconnect.updated': () Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 712, in async_schedule_update_ha_state self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 553, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 681, in _async_write_ha_state self.hass.states.async_set( File "/usr/src/homeassistant/homeassistant/core.py", line 1363, in async_set state = State( File "/usr/src/homeassistant/homeassistant/core.py", line 1049, in __init__ raise InvalidStateError( homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.q5_longterm_trip_data. State max length is 255 characters.
Exception in async_schedule_update_ha_state when dispatching 'audiconnect.updated': () Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 712, in async_schedule_update_ha_state self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 553, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 681, in _async_write_ha_state self.hass.states.async_set( File "/usr/src/homeassistant/homeassistant/core.py", line 1363, in async_set state = State( File "/usr/src/homeassistant/homeassistant/core.py", line 1049, in __init__ raise InvalidStateError( homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.q5_shortterm_trip_data. State max length is 255 characters.
```

**Comment by Nikotine1** [comment]
Same here:
`Exception in async_schedule_update_ha_state when dispatching 'audiconnect.updated': () Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 710, in async_schedule_update_ha_state self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 679, in _async_write_ha_state self.hass.states.async_set( File "/usr/src/homeassistant/homeassistant/core.py", line 1361, in async_set state = State( File "/usr/src/homeassistant/homeassistant/core.py", line 1047, in __init__ raise InvalidStateError( homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.audi_rs_e_tron_gt_shortterm_trip_user_reset. State max length is 255 characters.`

**Comment by jef-pearlman** [comment]
One more.  Every 10 minutes I get this error for these two entities (sensor.q5_shortterm_trip_data and sensor.q5_shortterm_trip_user_reset):

```
2022-06-24 09:58:49 ERROR (MainThread) [homeassistant.util.logging] Exception in async_schedule_update_ha_state when dispatching 'audiconnect.updated': ()
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 711, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 680, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1429, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1097, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.q5_shortterm_trip_data. State max length is 255 characters.

2022-06-24 09:58:49 ERROR (MainThread) [homeassistant.util.logging] Exception in async_schedule_update_ha_state when dispatching 'audiconnect.updated': ()
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 711, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 680, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1429, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1097, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.q5_shortterm_trip_user_reset. State max length is 255 characters.
```

Both states appear to be unavailable:
![Screenshot 2022-06-24 at 10-08-58 Developer Tools – Home Assistant](https://user-images.githubusercontent.com/8441584/175609488-d14caf70-e67d-449f-b355-b778a8f2e209.png)

Thanks!

**Comment by gllmlbrt** [comment]
Same here on my Q3. All sensors work great except for these short and long term trip for which I get the same error about the 255 characters. No need for me to share my logs.

**Comment by bartsmetdv** [comment]
Having the same issue Q3 as well, are there users for who trip data is actually working?

**Comment by D0ctorSnuggles** [comment]
I'm noticing the same with my A6:

Logger: homeassistant.util.logging
Source: util/logging.py:168
First occurred: 14:27:29 (256 occurrences)
Last logged: 16:42:37

```
Exception in async_schedule_update_ha_state when dispatching 'audiconnect.updated': () Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 704, in async_schedule_update_ha_state self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 556, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 673, in _async_write_ha_state self.hass.states.async_set( File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_set state = State( File "/usr/src/homeassistant/homeassistant/core.py", line 1140, in __init__ raise InvalidStateError( homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.audi_a6_avant_tfsi_e_xx_yy818e_shortterm_trip_data. State max length is 255 characters.

Exception in async_schedule_update_ha_state when dispatching 'audiconnect.updated': () Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 704, in async_schedule_update_ha_state self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 556, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 673, in _async_write_ha_state self.hass.states.async_set( File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_set state = State( File "/usr/src/homeassistant/homeassistant/core.py", line 1140, in __init__ raise InvalidStateError( homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.audi_a6_avant_tfsi_e_xx_yy818e_shortterm_trip_user_reset. State max length is 255 characters.
```

**Comment by coreywillwhat** [comment]
Thanks for your interest in this information!
Unfortunately, This is known to not be working at the moment. With API change, the structure is different and needs to be adapted. Closing to capture all related under a catch all issue: #344
