### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nickwild-999** [audiconnect/audi_connect_ha#132]
I recently installed this to use with an Audi Etron and it was working, but with an error, but now, upon a system reboot, I get the error, but no data back from the sensors.

No data on the integration has been changed, I have made no updates to the Ha system and the Audi App works.

Does anybody have any ideas?

```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/audiconnect/audi_api.py:75
Integration: Audi Connect
First occurred: 06:07:59 (1 occurrences)
Last logged: 06:07:59

Error setting up entr yxxx@xxx.com for audiconnect
Traceback (most recent call last):
  File "/config/custom_components/audiconnect/audi_api.py", line 53, in request
    async with self._session.request(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/audiconnect/audi_api.py", line 66, in request
    raise ClientResponseError(
  File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 116, in __exit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/audiconnect/__init__.py", line 106, in async_setup_entry
    return await data.update(utcnow())
  File "/config/custom_components/audiconnect/audi_account.py", line 162, in update
    if not await self.connection.update(None):
  File "/config/custom_components/audiconnect/audi_connect_account.py", line 112, in update
    vehicles_response = await self._audi_service.get_vehicle_information()
  File "/config/custom_components/audiconnect/audi_services.py", line 253, in get_vehicle_information
    req_rsp, rep_rsptxt = await self._api.request(
  File "/config/custom_components/audiconnect/audi_api.py", line 75, in request
    raise TimeoutError("Timeout error")
asyncio.exceptions.TimeoutError: Timeout error
```

**Comment by titiviking** [comment]
I believe Audi is facing some issues, as the app does not seem to work and the website either...

**Comment by nickwild-999** [comment]
Thanks it is back running again, but still showing errors

**Comment by chemgeek** [comment]
It is likely an Audi issue.  The software is terrible and stops working in the car often.  The Etron is a joke.

**Comment by nickwild-999** [comment]
Thanks @chemgeek 

> The Etron is a joke.

I quite agree, the app often fails to connect and there are MASSIVE software (and hardware) issues with the car itself. Drives like a dream, but anything else....!
