### ISSUE TITLE
Login to Audi service failed / Unable to obtail longTerm tripdata

### ISSUE THREAD

**Issue by bbr111** [audiconnect/audi_connect_ha#162]
Hi,

i have some error messages from audi_connet in my HA logs.

Maybe someone can help to fix this.

[custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds

2022-11-17 23:17:35.230 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Unable to obtain the vehicle longTerm tripdata of WAXXXXXXXXXXXXXXXX: 'NoneType' object is not subscriptable
2022-11-17 23:17:35.666 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] support_preheater set to False: 502
2022-11-17 23:17:35.673 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.audiconnect
2022-11-17 23:17:35.675 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.audiconnect
2022-11-17 23:17:35.679 INFO (MainThread) [homeassistant.components.switch] Setting up switch.audiconnect
2022-11-17 23:17:35.681 INFO (MainThread) [homeassistant.components.device_tracker] Setting up device_tracker.audiconnect
2022-11-17 23:17:35.684 INFO (MainThread) [homeassistant.components.lock] Setting up lock.audiconnect
2022-11-17 23:17:35.739 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform audiconnect
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
await asyncio.gather(*tasks)
File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity_platform.py", line 692, in _async_add_entity
await entity.add_to_platform_finish()
File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity.py", line 789, in add_to_platform_finish
self.async_write_ha_state()
File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
self._async_write_ha_state()
File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity.py", line 659, in _async_write_ha_state
self.hass.states.async_set(
File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/core.py", line 1469, in async_set
state = State(
File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/core.py", line 1130, in __init__
raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.audi_q5_tfsi_e_shortterm_trip_data. State max length is 255 characters.
2022-11-17 23:17:35.754 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up audiconnect platform for sensor
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
await asyncio.gather(*pending)
File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
await asyncio.gather(*tasks)
File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity_platform.py", line 692, in _async_add_entity
await entity.add_to_platform_finish()
File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity.py", line 789, in add_to_platform_finish
self.async_write_ha_state()
File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
self._async_write_ha_state()
File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity.py", line 659, in _async_write_ha_state
self.hass.states.async_set(
File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/core.py", line 1469, in async_set
state = State(
File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/core.py", line 1130, in __init__
raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.audi_q5_tfsi_e_shortterm_trip_data. State max length is 255 characters.

**Comment by JBO-Home22** [comment]
Same here for short and long term tripdata  ... Maybe it will be possible to eliminate short and long term tripdata
 
```
2022-11-20 13:43:03.070 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Unable to obtain the vehicle shortTerm tripdata of WAUZZZF48NA025173: 204, message='No Content', url=URL('https://mal-3a.prd.eu.dp.vwg-connect.com/api/bs/tripstatistics/v1/vehicles/WAUZZZF48NA025173/tripdata/shortTerm?type=list&from=1970-01-01T00:00:00Z&to=2022-11-20T14:13:02Z')
2022-11-20 13:43:03.171 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Unable to obtain the vehicle longTerm tripdata of WAUZZZF48NA025173: 204, message='No Content', url=URL('https://mal-3a.prd.eu.dp.vwg-connect.com/api/bs/tripstatistics/v1/vehicles/WAUZZZF48NA025173/tripdata/longTerm?type=list&from=1970-01-01T00:00:00Z&to=2022-11-20T14:13:03Z')
```

**Comment by simonepittis** [comment]
Hi, same here. we back with authentication error.... :-(

**Comment by rklueber** [comment]
Same here. Login fails. Having trouble to analyze the logs. 

I have 

````
logger:
  default: critical
  logs:
    custom_components.audiconnect: debug
````

but `home-assitant.log` and the output of `ha core logs` does not show any meaningfull lines for audiconnect.

What am I missing?

**Comment by simonepittis** [comment]
Logger: custom_components.audiconnect.audi_connect_account
Source: custom_components/audiconnect/audi_connect_account.py:94
Integration: Audi Connect
First occurred: 08:12:21 (18 occurrences)
Last logged: 08:19:59

    Login to Audi service failed, trying again in 10 seconds
    Login to Audi service failed: 'client_id'

**Comment by simonepittis** [comment]
I found a problem in two URLs:
- https://mal-1a.prd.ece.vwg-connect.com/
- https://msg.volkswagen.de/

Error 404

{"error" : {
"code" : "GW404",
"message" : "Not found",
"tracking-id" : "adf53afb-88b7-40d8-8c37-f5cca0773c0b"
} }

**Comment by Ronnie-J** [comment]
I have the same issue.

**Comment by simonepittis** [comment]
I will try to fix it this evening when I go back at home... because I read this:
Maintainers Wanted
Due to time limitations this project is not actively maintained anymore. It will continue to work as long as Audi does not change the API again. However, I'm open to someone else taking the lead. If you would like to become a maintainer, please contact me.

I will fix my self. if works I will share it for all ;-)

**Comment by shuntfield** [comment]
Yup it died for me yesterday, I'm not sure if its the version information in the audi_api.py file?

The version I have is 4.9.2 but the app is 4.14?

**Comment by simonepittis** [comment]
ok.... Back online ;-) probably WV fix it.
good

**Comment by simonepittis** [comment]
...but I will try to change the version to the last one

**Comment by shuntfield** [comment]
> ok.... Back online ;-) probably WV fix it. good

Yup, agreed mine has come back up too, 

VW meddling! 😡🤣

**Comment by Frankster-NL** [comment]
Still only errors here....

**Comment by simonepittis** [comment]
> Still only errors here....

reload the integration

**Comment by rklueber** [comment]
Just deleted and reinitiated the integration ... works! Thank you.

**Comment by Frankster-NL** [comment]
Working again!

**Comment by simonepittis** [comment]
ok Back to "Login Error Mode":

Logger: custom_components.audiconnect.audi_connect_account
Source: custom_components/audiconnect/audi_connect_account.py:94
Integration: Audi Connect
First occurred: 08:09:57 (190 occurrences)
Last logged: 09:38:17

    Login to Audi service failed: /signin-service/v1/09b6cbec-cd19-4589-82fd-363dfa8c24da@apps_vw-dilab_com/terms-and-conditions?relayState=7b39f9923bb8f3e3d35ea92c9244798a23513721&canChangeCountryOfResidence=true&updated=termsofuse&updated=dataprivacy
    Login to Audi service failed, trying again in 10 seconds
    Login to Audi service failed: /signin-service/v1/09b6cbec-cd19-4589-82fd-363dfa8c24da@apps_vw-dilab_com/terms-and-conditions?relayState=d8009a953664aee93b95532973ecfba3a1e0e4f1&canChangeCountryOfResidence=true&updated=termsofuse&updated=dataprivacy
    Login to Audi service failed: /signin-service/v1/09b6cbec-cd19-4589-82fd-363dfa8c24da@apps_vw-dilab_com/terms-and-conditions?relayState=e7baa065dfb442cc6478b31bdc37a65ccfafdb41&canChangeCountryOfResidence=true&updated=termsofuse&updated=dataprivacy
    Login to Audi service failed: /signin-service/v1/09b6cbec-cd19-4589-82fd-363dfa8c24da@apps_vw-dilab_com/terms-and-conditions?relayState=581adf1f9ddff318791c8d526022bd89e3d731c5&canChangeCountryOfResidence=true&updated=termsofuse&updated=dataprivacy

**Comment by rightsaidfred99** [comment]
Yep, same here

**Comment by gllmlbrt** [comment]
It is because y'all ned to accept the new T&C. I fixed this by going to the official app, log out completly, log in again, then you will be prompted to review/accept the T&C and once logged in the integration will work again.

**Comment by simonepittis** [comment]
> It is because y'all need to accept the new T&C. I fixed this by going to the official app, log out completly, log in again, then you will be prompted to review/accept the T&C and once logged in at the app, after reloading/restarting the integration will work again.

Thanks! fixed ;-)

**Comment by tieskuh** [comment]
> It is because y'all need to accept the new T&C. I fixed this by going to the official app, log out completly, log in again, then you will be prompted to review/accept the T&C and once logged in at the app, after reloading/restarting the integration will work again.

Thanks!!

**Comment by zaizuney** [comment]
> It is because y'all need to accept the new T&C. I fixed this by going to the official app, log out completly, log in again, then you will be prompted to review/accept the T&C and once logged in at the app, after reloading/restarting the integration will work again.

jip, fixed it, thx!

**Comment by shuntfield** [comment]
Yeah that's fixed it for me too ☺️

**Comment by woopstar** [comment]
Seems they have added Throttle to the api

```2023-01-19 20:51:43.176 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds
2023-01-19 20:51:54.328 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed: /signin-service/v1/09b6cbec-cd19-4589-82fd-363dfa8c24da@apps_vw-dilab_com/login/authenticate?relayState=78d0a1ce517c701b215561864434801dd3e2086f&nextButtonDisabled=true&enableNextButtonAfterSeconds=3600&error=login.error.throttled```

**Comment by tieskuh** [comment]
> Seems they have added Throttle to the api
> 
> ```
> 2023-01-19 20:51:54.328 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed: /signin-service/v1/09b6cbec-cd19-4589-82fd-363dfa8c24da@apps_vw-dilab_com/login/authenticate?relayState=78d0a1ce517c701b215561864434801dd3e2086f&nextButtonDisabled=true&enableNextButtonAfterSeconds=3600&error=login.error.throttled```
> ```

Same here...

**Comment by tieskuh** [comment]
But it's strange the iPhone app (connected to WiFi) continues to work. So it isn't rate limiting on IP address.

**Comment by tieskuh** [comment]
Trying to log in to My Audi I get this message:

<img width="341" alt="image" src="https://user-images.githubusercontent.com/115901851/213713081-caba7b5f-a3c1-47ec-a958-3354795997bc.png">

Which is Dutch for too many login attempts with wrong credentials. Which I'm pretty sure I didn't do.

**Comment by woopstar** [comment]
I changed my password using the reset password function, and things started to work again

**Comment by tieskuh** [comment]
> I changed my password using the reset password function, and things started to work again

Thanks! That worked for me too!
