### ISSUE TITLE
Integration failed to set up - KeyError: 'access_token'

### ISSUE THREAD

**Issue by titiviking** [audiconnect/audi_connect_ha#201]
```
2023-09-22 15:10:08.720 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry myemail@provider.com for audiconnect
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/audiconnect/__init__.py", line 111, in async_setup_entry
return await data.update(utcnow())
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/audiconnect/audi_account.py", line 162, in update
if not await self.connection.update(None):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/audiconnect/audi_connect_account.py", line 112, in update
vehicles_response = await self._audi_service.get_vehicle_information()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/audiconnect/audi_services.py", line 245, in get_vehicle_information
"Authorization": "Bearer " + self.audiToken["access_token"],
~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'access_token'
```

**Comment by cdnninja** [comment]
Is this still an issue?

**Comment by coreywillwhat** [comment]
issue has been stale for longer than 60 days. Closing this issue.
Please submit a new issue if anything comes up.

**Comment by jonny190** [comment]
After updating this to the latest update today i'm also getting this
![image](https://github.com/audiconnect/audi_connect_ha/assets/8059327/5824f3a9-d567-4b88-a726-1cfae1943f17)
