### ISSUE TITLE
Login to Audi service failed

### ISSUE THREAD

**Issue by timo002** [audiconnect/audi_connect_ha#501]
**Describe the bug**
Since a few days my integration is not working anymore.  I'm not getting any new data, the integration also shows: Failed to set up

**Screenshot**
![afbeelding](https://github.com/user-attachments/assets/be6576ec-31e2-48c4-8bd6-3347e0287627)

**Logfile**
LOGIN: Login to Audi service failed: 'Location'
LOGIN: Login to Audi service failed: Cannot connect to host content.app.my.audi.com:443 ssl:default [Timeout while contacting DNS servers]
LOGIN: Login to Audi service failed: 'NoneType' object has no attribute 'get'

**Your Vehicle Details**
Model: A3
Year: 2022
Type:  Hybrid
Region: EU

**Comment by GMTheDoctor** [comment]
Same here today

**Comment by tmooz** [comment]
Same here. SQ7 from Germany

**Comment by rightsaidfred99** [comment]
VW devs are the worst at breaking stuff

**Comment by olivierdc94** [comment]
Same here Q4, Belgium

**Comment by Ragonz** [comment]
Same, 2022 etron, UK

**Comment by 1979SAJ** [comment]
This helped me to reconnect to my audi through HA

1: go to https://my.audi.com/ and login with your account  

2: Change your Country to another country (for instance USA) 

3: Logout of your account

4: Logon to your account again and change country back to the correct one

5: Log out of your account 

6: Try to reconnect with home assistant

Hope it work for your all

**Comment by rightsaidfred99** [comment]
I got it working again, but I just logged in and logged out. I wasn't able to change my country

**Comment by doubleGG82** [comment]
same problem Q4 Belgium
logging out and back in does not work unfortunately

Logger: homeassistant.config_entries
Bron: config_entries.py:640
Eerst voorgekomen: 15:43:29 (1 gebeurtenissen)
Laatst gelogd: 15:43:29

Error setting up entry xxxxxxxxxx for audiconnect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/audiconnect/__init__.py", line 144, in async_setup_entry
    return await data.update(utcnow())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/audiconnect/audi_account.py", line 162, in update
    if not await self.connection.update(None):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/audiconnect/audi_connect_account.py", line 113, in update
    vehicles_response = await self._audi_service.get_vehicle_information()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/audiconnect/audi_services.py", line 269, in get_vehicle_information
    "Authorization": "Bearer " + self.audiToken["access_token"],
                                 ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'access_token'

**Comment by lexathon** [comment]
Did you try logging in from a web browser. This issue seems to be down to some sort of user acceptance form that pops up when you try to login. It needs to be agreed prior to successful login.

**Comment by doubleGG82** [comment]
yes, tried logging in with webbrowser, did't get any pop-up
I have reinstalled the integration, without success

**Comment by doubleGG82** [comment]
I logged out from the app on my phone, and logged back in.
First time I got an error, on a second try the login succeed, and the HA integration also works again
Seems to be a glitch at Audi server

**Comment by EBOOZ** [comment]
Looks like they changed the backend (again). my.audi.com gives me the following message:
"_Audi connect: Coming soon in the myAudi app

To make all information and services for your Audi even more accessible to you, we are currently renewing our digital services.

Therefore, you will soon find the new myAudi customer zone here with your digital instruction manual, options to contact your Audi dealer, and many other important applications.

With the launch of the new myAudi customer zone, your Audi connect services will only be available via the myAudi app._"

![image](https://github.com/user-attachments/assets/e8ccc239-8a9e-44e9-a015-1b7f312c3ffc)

**Comment by oleg-d** [comment]
What helped me is log out of the mobile audi app, and log back in. YOu then will get asked to consent to some stuff, i just rejected it. Then the HA integration started working again. 
This is not the first time this has happened, its just common now that Audi requires you to "consent" to some policy changes or whatever every so often and the HA app breaks but easy enough resolution.

**Comment by Bluemerlin** [comment]
> What helped me is log out of the mobile audi app, and log back in. YOu then will get asked to consent to some stuff, i just rejected it. Then the HA integration started working again. This is not the first time this has happened, its just common now that Audi requires you to "consent" to some policy changes or whatever every so often and the HA app breaks but easy enough resolution.

This worked for me, I was having the same issue. Thank you.

**Comment by coreywillwhat** [comment]
Closing due to lack of response. Please open a new issue if anything comes up. Thank you!
